from init_env import init_environment

env = init_environment("mlibrary qt5 geant4 clhep")

pluginSources = Split("""
	loadConstants.cc
	loadSensitivePars.cc
	hitDigitization.cc
	showConstants.cc
	gDynamicFactory.cc
    """)

# standard pre and suffix for gemc plugins
env.Replace(SHLIBSUFFIX = ".gplugin")
env.Replace(SHLIBPREFIX = "")

ctof_dll = env.SharedLibrary( source = pluginSources,  target = "ctof")

